### PR TITLE
Fix typo in readme

### PR DESCRIPTION
**Pull request by cherryblossom000**
`minuetes` → `minutes`

### CODE REVIEW

**Comment by covers1624** [comment]
Sorry, We don't accept PR's for minor single line spelling changes.

**Comment by patrickklaeren** [comment]
I actually think it's unreasonable to state that as a case for rejection. Plenty of people want to translate or use a screen reader, it's a simple typo to correct @covers1624

**Comment by TheCurle** [comment]
MCPConfig is not designed for end users. If someone is exploring this repository and needs this fix to be able to understand what's going on... i dread to imagine how they'll get on with the actual code.

As it stands, this is a completely pointless PR in the intended scope of the repository.

**Comment by patrickklaeren** [comment]
> MCPConfig is not designed for end users. If someone is exploring this repository and needs this fix to be able to understand what's going on... i dread to imagine how they'll get on with the actual code.
> 
> As it stands, this is a completely pointless PR in the intended scope of the repository.

I am lost for words. As you please.

**Pull request closed without merging**
