### PR TITLE
Add 22w03a

### PR DESCRIPTION
**Pull request by coehlrich**
Made a week ago just didn't make a PR until now

### CODE REVIEW

**Comment by LexManos** [comment]
Got a diff from 1.18.1?

**Comment by coehlrich** [comment]
Here's the difference in patch files: https://gist.github.com/coehlrich/7aba64bf00ad5d83e42eb4018a641a4b

**Comment by sciwhiz12** [comment]
Here's a diff between 1.18.1 and 22w03a: https://gist.github.com/sciwhiz12/09970d80e4f162d8bfbf8ae3f1782680. ([1.18.1-22w03a.diff.txt](https://github.com/MinecraftForge/MCPConfig/files/7960576/1.18.1-22w03a.diff.txt))


Made using `git diff --no-index versions/release/1.18.1/projects/joined/src/main/java versions/snapshot/1.18/22w03a/projects/joined/src/main/java > 22w03a.diff` (after preprocessing using `dos2unix` to get rid of line ending changes, via `find <dir> -type f -print0 | xargs -0 -n 1 -P 4 dos2unix` in a WSL terminal).

**Comment by LexManos** [comment]
Ah, the great logging refactor, Not a bad diff, my notes on what should be manually fixed:
[Lambda p_202360_ -> p_95076_](https://gist.github.com/sciwhiz12/09970d80e4f162d8bfbf8ae3f1782680#file-1-18-1-22w03a-diff-L2433)
[Lambda p_202369_ -> p_169091_](https://gist.github.com/sciwhiz12/09970d80e4f162d8bfbf8ae3f1782680#file-1-18-1-22w03a-diff-L2446)
[Lambda p_202367_ -> p_95088_](https://gist.github.com/sciwhiz12/09970d80e4f162d8bfbf8ae3f1782680#file-1-18-1-22w03a-diff-L2475)
[Lambda p_202365_ -> p_95086_](https://gist.github.com/sciwhiz12/09970d80e4f162d8bfbf8ae3f1782680#file-1-18-1-22w03a-diff-L2487)

Broken Patch: Needs int because ambiguous method call [Client](https://gist.github.com/coehlrich/7aba64bf00ad5d83e42eb4018a641a4b#file-output-diff-L65), [Joined](https://gist.github.com/coehlrich/7aba64bf00ad5d83e42eb4018a641a4b#file-output-diff-L133)

**Comment by coehlrich** [comment]
Added patches and fixed lambda parameter names and updated patches gist

**Pull request merged**
